// <auto-generated />
namespace OddMarathon.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sportWithId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sportWithId));
        
        string IMigrationMetadata.Id
        {
            get { return "201809121620208_sportWithId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
